# Generated by Django 6.0.5 on 2026-05-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specimens", "0005_alter_specimenrecord_collecting_trip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specimenrecord",
            name="usi",
            field=models.CharField(
                help_text="Enter the specimen's unique identifier number",
                max_length=15,
                unique=True,
                verbose_name="Unique Specimen Identifier",
            ),
        ),
    ]
