# Generated by Django 6.0.7 on 2026-07-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specimens", "0006_alter_specimenrecord_usi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specimenrecord",
            name="method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Net", "Net"),
                    ("Reared", "Reared"),
                    ("Trap", "Trap"),
                    ("UV trap", "UV trap"),
                    ("Light", "Light"),
                    ("LED light", "LED light"),
                    ("LED light sheet", "LED light sheet"),
                    ("MV light", "MV light"),
                    ("MV light sheet", "MV light sheet"),
                    ("UV light", "UV light"),
                    ("UV light sheet", "UV light sheet"),
                    ("UV/MV light sheet", "UV/MV light sheet"),
                    ("UV/MV/LED light sheet", "UV/MV/LED light sheet"),
                    ("Bait", "Bait"),
                    ("By hand", "By hand"),
                    ("Sweep", "Sweep"),
                ],
                default="",
                help_text="Select the method used to collected the specimen",
                max_length=50,
            ),
        ),
    ]
