# Generated by Django 6.0.7 on 2026-07-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specimens", "0007_alter_specimenrecord_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="specimenrecord",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
