# Generated by Django 6.0.7 on 2026-07-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specimens", "0008_specimenrecord_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="specimenrecord",
            name="short_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
