# Generated by Django 6.0.8 on 2026-08-29 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("specimens", "0009_specimenrecord_short_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specimenrecord",
            name="qr_code",
        ),
    ]
