# Generated by Django 6.0.8 on 2026-08-26 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0019_alter_customimage_sex_alter_customimage_stage_and_more"),
        ("taxonomy", "0016_alter_family_order_alter_genus_tribe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="featured_image",
            field=models.OneToOneField(
                blank=True,
                help_text="Select an image to represent this family",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="featured_image",
            field=models.OneToOneField(
                blank=True,
                help_text="Select an image to represent this order",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="featured_image",
            field=models.OneToOneField(
                blank=True,
                help_text="Select an image to represent this species",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
