# Generated by Django 6.0.8 on 2026-08-26 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0009_delete_habitatimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlantImage",
        ),
    ]
