# Generated by Django 6.0.8 on 2026-08-26 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0010_delete_plantimage"),
        ("pages", "0002_alter_speciespage_species"),
        ("taxonomy", "0016_alter_family_order_alter_genus_tribe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insectimage",
            name="species",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the species in the image, if it is identified",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insect_images",
                to="taxonomy.species",
            ),
        ),
        migrations.AlterField(
            model_name="insectimage",
            name="species_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the species page to which this image belongs, if the insect in the image                   is identified",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insect_images",
                to="pages.speciespage",
            ),
        ),
    ]
