# Generated by Django 6.0.8 on 2026-08-26 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0011_alter_insectimage_species_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InsectImage",
        ),
    ]
