# Generated by Django 6.0.8 on 2026-08-26 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0012_delete_insectimage"),
        ("specimens", "0009_specimenrecord_short_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specimenrecordimage",
            name="usi",
            field=models.ForeignKey(
                help_text="Select the specimen in the image",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specimen_images",
                to="specimens.specimenrecord",
            ),
        ),
    ]
