# Generated by Django 6.0.8 on 2026-08-26 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0013_alter_specimenrecordimage_usi"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SpecimenRecordImage",
        ),
    ]
