# Generated by Django 6.0.8 on 2026-08-26 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0012_alter_county_state_alter_gps_locality_and_more"),
        ("images", "0014_delete_specimenrecordimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseliveimage",
            name="collecting_trip",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the collecting trip during which the image was taken",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="geography.collectingtrip",
            ),
        ),
        migrations.AlterField(
            model_name="baseliveimage",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the country in which the image was taken",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="geography.country",
            ),
        ),
        migrations.AlterField(
            model_name="baseliveimage",
            name="county",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the county in which the image was taken",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="geography.county",
            ),
        ),
        migrations.AlterField(
            model_name="baseliveimage",
            name="gps",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the GPS coordinates at which the image was taken",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="geography.gps",
            ),
        ),
        migrations.AlterField(
            model_name="baseliveimage",
            name="locality",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the locality at which the image was taken",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="geography.locality",
            ),
        ),
        migrations.AlterField(
            model_name="baseliveimage",
            name="state",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the state in which the image was taken",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="geography.state",
            ),
        ),
    ]
