# Generated by Django 6.0.8 on 2026-08-26 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0015_alter_baseliveimage_collecting_trip_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BaseLiveImage",
        ),
    ]
