# Generated by Django 6.0.8 on 2026-08-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0016_delete_baseliveimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="image_type",
            field=models.CharField(
                choices=[
                    ("specimen", "Specimen Record"),
                    ("insect", "Insect"),
                    ("plant", "Plant"),
                    ("habitat", "Habitat"),
                ],
                default="specimen",
                help_text="Select the type of image",
                max_length=20,
            ),
        ),
    ]
