# Generated by Django 6.0.8 on 2026-08-26 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0012_alter_county_state_alter_gps_locality_and_more"),
        ("images", "0017_customimage_image_type"),
        ("pages", "0002_alter_speciespage_species"),
        ("specimens", "0009_specimenrecord_short_code"),
        ("taxonomy", "0016_alter_family_order_alter_genus_tribe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="collecting_trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="custom_images",
                to="geography.collectingtrip",
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="common_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customimage",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="custom_images",
                to="geography.country",
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="county",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="custom_images",
                to="geography.county",
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="gps",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="custom_images",
                to="geography.gps",
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="habitat_species_page",
            field=models.ManyToManyField(
                blank=True, related_name="habitat_images", to="pages.speciespage"
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="locality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="custom_images",
                to="geography.locality",
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="plant_species_page",
            field=models.ManyToManyField(
                blank=True, related_name="plant_images", to="pages.speciespage"
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dorsal", "Dorsal"),
                    ("ventral", "Ventral"),
                    ("lateral", "Lateral"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="scientific_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customimage",
            name="sex",
            field=models.CharField(
                choices=[
                    ("male", "male"),
                    ("female", "female"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="species",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="insect_images",
                to="taxonomy.species",
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="species_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="insect_images",
                to="pages.speciespage",
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="specimen_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="images",
                to="specimens.specimenrecord",
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="stage",
            field=models.CharField(
                choices=[
                    ("egg", "egg"),
                    ("larva", "larva"),
                    ("nymph", "nymph"),
                    ("pupa", "pupa"),
                    ("adult", "adult"),
                ],
                default="adult",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="custom_images",
                to="geography.state",
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="status",
            field=models.CharField(
                choices=[("wild", "Wild"), ("reared", "Reared"), ("bred", "Bred")],
                default="wild",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customrendition",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="renditions",
                to="images.customimage",
            ),
        ),
    ]
