# Generated by Django 6.0.8 on 2026-08-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0018_customimage_collecting_trip_customimage_common_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customimage",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "male"),
                    ("female", "female"),
                    ("unknown", "unknown"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("egg", "egg"),
                    ("larva", "larva"),
                    ("nymph", "nymph"),
                    ("pupa", "pupa"),
                    ("adult", "adult"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("wild", "Wild"), ("reared", "Reared"), ("bred", "Bred")],
                max_length=10,
            ),
        ),
    ]
