# Generated by Django 6.0.8 on 2026-08-26 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0012_alter_county_state_alter_gps_locality_and_more"),
        ("images", "0019_alter_customimage_sex_alter_customimage_stage_and_more"),
        ("pages", "0002_alter_speciespage_species"),
        ("specimens", "0009_specimenrecord_short_code"),
        ("taxonomy", "0017_family_featured_image_order_featured_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customimage",
            name="collecting_trip",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the collecting trip during which the image was taken, if it was taken during one",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="custom_images",
                to="geography.collectingtrip",
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="common_name",
            field=models.CharField(
                blank=True,
                help_text="Enter the common name of the plant in the imagee, if it has one",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the country in which the image was taken, if known",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="custom_images",
                to="geography.country",
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="county",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the county in which the image was taken, if known",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="custom_images",
                to="geography.county",
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="gps",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the GPS coordinates at which the image was taken, if known",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="custom_images",
                to="geography.gps",
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="habitat_species_page",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the insect species page(s) to which this habitat image should belong",
                related_name="habitat_images",
                to="pages.speciespage",
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="locality",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the locality at which the image was taken, if known",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="custom_images",
                to="geography.locality",
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="plant_species_page",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the insect species page(s) to which this plant image should belong",
                related_name="plant_images",
                to="pages.speciespage",
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dorsal", "Dorsal"),
                    ("ventral", "Ventral"),
                    ("lateral", "Lateral"),
                ],
                help_text="Select the position in which the specimen was taken",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="scientific_name",
            field=models.CharField(
                blank=True,
                help_text="Enter the scientific name of the plant in the image",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "male"),
                    ("female", "female"),
                    ("unknown", "unknown"),
                ],
                help_text="Select the sex of the insect in the image, if known",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="species",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the insect species in the image",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="insect_images",
                to="taxonomy.species",
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="species_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the insect species page to which this image should belong",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="insect_images",
                to="pages.speciespage",
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="specimen_record",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the specimen record to which this image belongs",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="images",
                to="specimens.specimenrecord",
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("egg", "egg"),
                    ("larva", "larva"),
                    ("nymph", "nymph"),
                    ("pupa", "pupa"),
                    ("adult", "adult"),
                ],
                help_text="Select the stage of the insect in the image",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="state",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the state in which the image was taken, if known",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="custom_images",
                to="geography.state",
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("wild", "Wild"), ("reared", "Reared"), ("bred", "Bred")],
                help_text="Select the status of the insect in the image",
                max_length=10,
            ),
        ),
    ]
