# Generated by Django 6.0.8 on 2026-08-29 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0012_alter_county_state_alter_gps_locality_and_more"),
        ("images", "0020_alter_customimage_collecting_trip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customimage",
            name="collecting_trip",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the collecting trip during which the image was taken, if it was taken                    during one",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="custom_images",
                to="geography.collectingtrip",
            ),
        ),
    ]
